<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EM13 extends Model
{
    protected $table = 'EM13';
    public $timestamps = false;
    protected $fillable = [
        'EMID',
        'EMME',
        'ENME',
        'TLNO',
        'COID',
        'DVID',
        'DPID',
        'POID',
        'IDNO',
        'PASSPORT',
        'COUNTRY_ID',
        'DF_CLAS',
        'SEXX',
        'MARR',
        'BLOD',
        'BELO',
        'BIRT',
        'BKID',
        'BANK',
        'CONT',
        'FAX',
        'TELE',
        'ZIP',
        'ADD1',
        'ADD2',
        'E_MAIL',
        'CHKM',
        'YEARS_STR',
        'YEARS_ACU',
        'VAC',
        'ACU_LAB',
        'ACU_HLT',
        'TAXED',
        'REV',
        'PRIN_SEQ',
        'ID_CARD',
        'CARDED',
        'CARD_CLAS',
        'ID_CLAS',
        'CST_TYPE',
        'ONDT',
        'DATE_1',
        'DATE_2',
        'DATE_3',
        'TEST_SAL',
        'DATE_4',
        'DATE_5',
        'DATE_6',
        'DATE_7',
        'DATE_8',
        'DATE_9',
        'OFDT',
        '留職停薪否',
        '正職否',
        '計薪別',
        'VOICE',
        '行動電話',
        '連絡人行動電話',
        '職等',
        '職級',
        '照片',
        '業績等級',
        'IDSTATUS',
        'msrepl_tran_version',
        'Type_',
    ];
}
