<template>
  <div class="loadingio-spinner-eclipse-1r0dj7ytqkz">
      <div class="ldio-lz54hi6h0qn">
    <div></div>
    </div></div>
</template>

<script>

export default {
     name: "Loader",
}
</script>
<style type="text/css">
@keyframes ldio-lz54hi6h0qn {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-lz54hi6h0qn div {
  position: absolute;
  animation: ldio-lz54hi6h0qn 1s linear infinite;
  width: 136.96px;
  height: 136.96px;
  top: 38.52px;
  left: 38.52px;
  border-radius: 50%;
  box-shadow: 0 2.5680000000000005px 0 0 #1d0e0b;
  transform-origin: 68.48px 69.76400000000001px;
}
.loadingio-spinner-eclipse-1r0dj7ytqkz {
  width: 214px;
  height: 214px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-lz54hi6h0qn {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-lz54hi6h0qn div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>